In [3]:
import torch
import numpy as np

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

shape = (3,4,2) # C, H, W
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

tensor([[1, 2],
        [3, 4]])
Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6089, 0.5451],
        [0.1112, 0.0369]]) 

Random Tensor: 
 tensor([[[0.2068, 0.8868],
         [0.6525, 0.1443],
         [0.3963, 0.5516],
         [0.8273, 0.6318]],

        [[0.2205, 0.5054],
         [0.9431, 0.8830],
         [0.8961, 0.0022],
         [0.3027, 0.0779]],

        [[0.0491, 0.7108],
         [0.9291, 0.0983],
         [0.6988, 0.5663],
         [0.5580, 0.9104]]]) 

Ones Tensor: 
 tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]]) 

Zeros Tensor: 
 tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.

In [3]:
tensor = torch.rand(3,4)
cuda0 = torch.device('cuda')
tensor = tensor.to(cuda0)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")
other = torch.randn((), dtype=torch.float64, device=cuda0)
print(other.device)

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cuda:0
cuda:0


In [4]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

### Indexing & Slicing

In [26]:
tensor = torch.rand(2, 3, 4)
tensor2 = torch.rand(2, 3, 4)
print(tensor)
print(tensor2)

tensor([[[0.1446, 0.8874, 0.4613, 0.4684],
         [0.6871, 0.8136, 0.0994, 0.3898],
         [0.7995, 0.5936, 0.8933, 0.0302]],

        [[0.5760, 0.1833, 0.3036, 0.8013],
         [0.3347, 0.9959, 0.1989, 0.1865],
         [0.7856, 0.6544, 0.0725, 0.7021]]])
tensor([[[0.8017, 0.9123, 0.4146, 0.7147],
         [0.6186, 0.1658, 0.7830, 0.7320],
         [0.0041, 0.7663, 0.6325, 0.7809]],

        [[0.9474, 0.5979, 0.2683, 0.7928],
         [0.7629, 0.1135, 0.9531, 0.5871],
         [0.3024, 0.0652, 0.5343, 0.1839]]])


In [27]:
print('First channel: ', tensor[0])
print('First Row: ', tensor[:, :, 0])
print('First Column', tensor[..., 0])

First channel:  tensor([[0.1446, 0.8874, 0.4613, 0.4684],
        [0.6871, 0.8136, 0.0994, 0.3898],
        [0.7995, 0.5936, 0.8933, 0.0302]])
First Row:  tensor([[0.1446, 0.6871, 0.7995],
        [0.5760, 0.3347, 0.7856]])
First Column tensor([[0.1446, 0.6871, 0.7995],
        [0.5760, 0.3347, 0.7856]])


### Arithmetic operations

In [46]:
# Matrix multiplication
y1 = tensor[0] @ tensor2[0].T
y2 = tensor[0].matmul(tensor2[0].T)
# element-wise product
z1 = tensor * tensor2
print(y1)
print(y1 == y2)
print(z1)

# In-place operation
tensor.add_(5) # 메소드에 _붙이면 반환없이 바로 적용되게 구현해놓음
print(tensor)

tensor([[29.8845, 23.9342, 23.1768],
        [30.0460, 23.9167, 22.8323],
        [30.0075, 24.3081, 22.8855]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
tensor([[[ 8.1327,  9.9330,  4.3369,  7.4819],
         [ 6.6108,  1.7926,  7.9080,  7.6052],
         [ 0.0442,  8.1183,  6.8904,  7.8326]],

        [[10.0193,  6.0884,  2.7646,  8.5635],
         [ 7.8844,  1.2476,  9.7202,  5.9804],
         [ 3.2615,  0.6946,  5.3820,  1.9677]]])
tensor([[[15.1446, 15.8874, 15.4613, 15.4684],
         [15.6871, 15.8136, 15.0994, 15.3898],
         [15.7995, 15.5936, 15.8933, 15.0302]],

        [[15.5760, 15.1833, 15.3036, 15.8013],
         [15.3347, 15.9959, 15.1989, 15.1865],
         [15.7856, 15.6544, 15.0725, 15.7021]]])


In [28]:
t0 = torch.cat([tensor, tensor2], dim=0)
print(t0)

t1 = torch.cat([tensor, tensor2], dim=1)
print(t1)

t2 = torch.cat([tensor, tensor2], dim=2)
print(t2)

tensor([[[0.1446, 0.8874, 0.4613, 0.4684],
         [0.6871, 0.8136, 0.0994, 0.3898],
         [0.7995, 0.5936, 0.8933, 0.0302]],

        [[0.5760, 0.1833, 0.3036, 0.8013],
         [0.3347, 0.9959, 0.1989, 0.1865],
         [0.7856, 0.6544, 0.0725, 0.7021]],

        [[0.8017, 0.9123, 0.4146, 0.7147],
         [0.6186, 0.1658, 0.7830, 0.7320],
         [0.0041, 0.7663, 0.6325, 0.7809]],

        [[0.9474, 0.5979, 0.2683, 0.7928],
         [0.7629, 0.1135, 0.9531, 0.5871],
         [0.3024, 0.0652, 0.5343, 0.1839]]])
tensor([[[0.1446, 0.8874, 0.4613, 0.4684],
         [0.6871, 0.8136, 0.0994, 0.3898],
         [0.7995, 0.5936, 0.8933, 0.0302],
         [0.8017, 0.9123, 0.4146, 0.7147],
         [0.6186, 0.1658, 0.7830, 0.7320],
         [0.0041, 0.7663, 0.6325, 0.7809]],

        [[0.5760, 0.1833, 0.3036, 0.8013],
         [0.3347, 0.9959, 0.1989, 0.1865],
         [0.7856, 0.6544, 0.0725, 0.7021],
         [0.9474, 0.5979, 0.2683, 0.7928],
         [0.7629, 0.1135, 0.9531, 0.5871],
 

In [39]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.063037872314453 <class 'float'>


### Type Casting

In [54]:
print(tensor.tolist())
print(tensor.numpy())

[[[15.144573211669922, 15.887393951416016, 15.461296081542969, 15.468414306640625], [15.687061309814453, 15.813627243041992, 15.099424362182617, 15.389839172363281], [15.799461364746094, 15.593647003173828, 15.893321990966797, 15.03024673461914]], [[15.57595443725586, 15.183319091796875, 15.303594589233398, 15.801288604736328], [15.334693908691406, 15.995878219604492, 15.198944091796875, 15.186508178710938], [15.785558700561523, 15.65438461303711, 15.072513580322266, 15.70210075378418]]]
[[[15.144573 15.887394 15.461296 15.468414]
  [15.687061 15.813627 15.099424 15.389839]
  [15.799461 15.593647 15.893322 15.030247]]

 [[15.575954 15.183319 15.303595 15.801289]
  [15.334694 15.995878 15.198944 15.186508]
  [15.785559 15.654385 15.072514 15.702101]]]
