In [1]:
import torch
import numpy as np

In [16]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

shape = (3,4,2) # C, H, W
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

tensor([[1, 2],
        [3, 4]])
Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9240, 0.8233],
        [0.9409, 0.8618]]) 

Random Tensor: 
 tensor([[[0.5665, 0.7693],
         [0.3697, 0.3020],
         [0.9237, 0.1976],
         [0.8833, 0.4511]],

        [[0.6221, 0.5965],
         [0.4776, 0.8125],
         [0.0918, 0.7360],
         [0.7826, 0.6637]],

        [[0.0945, 0.2235],
         [0.4605, 0.9195],
         [0.5327, 0.3048],
         [0.9195, 0.8674]]]) 

Ones Tensor: 
 tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]]) 

Zeros Tensor: 
 tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.

In [27]:
tensor = torch.rand(3,4)
cuda0 = torch.device('cuda')
tensor = tensor.to(cuda0)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")
other = torch.randn((), dtype=torch.float64, device=cuda0)
print(other.device)

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cuda:0
cuda:0
